package lapr.project.ui;

import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import lapr.project.controller.ChangeApplicationController;
import lapr.project.model.Application;
import lapr.project.model.EventCenter;
import lapr.project.model.User;
import lapr.project.utils.AuthenticationService;

/**
 *
 * @author RuiSL
 */
public class ChangeApplicationUI extends JPanel {

    private static final long serialVersionUID = 1L;
    private final EventCenter eventCenter;
    private final ChangeApplicationController changeController;
    private String[] applicationList;
    private User u;
    private Application a;

    // Variables declaration - do not modify                     
    private JList<String> applicationSelectList;
    private javax.swing.JPanel changeApplicationDataInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelApplicationSelect;
    // End of variables declaration                   

    // private JPanel changeApplicationDataInput;

    /**
     * Creates new form ChangeApplicationUI
     */
    public ChangeApplicationUI(EventCenter eventCenter, ChangeApplicationController changeController) {
        this.eventCenter = eventCenter;
        this.changeController = changeController;

        AuthenticationService authentication = new AuthenticationService();
        u = authentication.getAuthenticatedUser();
        String userName = u.getUsername();
        applicationList = changeController.getApplicationsAsString(userName);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelApplicationSelect = new javax.swing.JLabel();
        changeApplicationDataInput = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicationSelectList = new JList<String>(applicationList);

        labelApplicationSelect.setText("Please select Application");

        javax.swing.GroupLayout changeApplicationDataInputLayout = new javax.swing.GroupLayout(changeApplicationDataInput);
        changeApplicationDataInput.setLayout(changeApplicationDataInputLayout);
        changeApplicationDataInputLayout.setHorizontalGroup(
                changeApplicationDataInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 175, Short.MAX_VALUE)
        );
        changeApplicationDataInputLayout.setVerticalGroup(
                changeApplicationDataInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 128, Short.MAX_VALUE)
        );

        applicationSelectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        applicationSelectList.setToolTipText("");
        applicationSelectList.addListSelectionListener((ListSelectionEvent evt) -> {
            applicationSelectListValueChanged(evt);
        });
        jScrollPane1.setViewportView(applicationSelectList);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelApplicationSelect, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(changeApplicationDataInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelApplicationSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(changeApplicationDataInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
        );
    }
// </editor-fold>                        

    private void applicationSelectListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        Object a = applicationSelectList.getSelectedValue();
        String applicationString = (String) a;
        Application ap = changeController.getApplication(applicationString);
        changeController.selectApplication(ap);
        JLabel label = new JLabel("Application chosen");
        label.setVisible(true);
        changeApplicationDataInput.setVisible(true);
        a = ap;
    }
}
